version: '3.7'

services:
  db:
    hostname: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  currency-api:
    build: .
    environment:
    ports:
      - "3030:3030"
    depends_on:
      - db
    volumes:
      - ./config/config.yaml:/etc/genesis-academy/currency-api/config.yaml:ro
    restart: unless-stopped

volumes:
  db-data: